= Quarkus PrimeFaces

include::./includes/attributes.adoc[]

A Quarkus extension that lets you utilize https://www.primefaces.org/showcase/[PrimeFaces] and https://github.com/primefaces-extensions[PrimeFaces Extensions] make JSF development so much easier!

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.primefaces:quarkus-primefaces` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.primefaces</groupId>
    <artifactId>quarkus-primefaces</artifactId>
    <version>{project-version}</version>
</dependency>
<dependency>
    <groupId>io.quarkiverse.primefaces</groupId>
    <artifactId>quarkus-primefaces-extensions</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Limitations

When creating a GraalVM Native image you may need to change some of your code to be native friendly and some features may not be available to use in Native mode.

WARNING: FeedReader not supported. Rome library uses JDOM XML parsing and we did not spend the time to investigate for a lightly used component.

WARNING: EL expressions which use reflection may run into issues with things like List size() or Enum name() as they are not bean compliant method names. You might need to change your EL expression or add helper code to achieve what you want.

== Versioning

The versioning of this extension will follow the pattern `[quarkus.version].[primefaces.version].[patch]`. For example:

[cols="1,1"]
|===
|Version |Explanation

|2.12.1
|Quarkus 2 (EE8), PrimeFaces 12, Revision 1

|3.12.0
| Quarkus 3 (EEE10), PrimeFaces 12, Revision 0
|===